---
- alias: Garage on
  trigger:
    platform: state
    entity_id: input_boolean.radio_garage
    to: 'on'
  condition:
    - condition: state
      entity_id: media_player.ae_garage_airtunes_speaker
      state: 'off'
  action:
    - service: media_player.turn_on
      entity_id: media_player.ae_garage_airtunes_speaker
    - service: input_number.increment
      entity_id: input_number.active_speakers
    - service: media_player.volume_set
      data:
        entity_id: media_player.ae_garage_airtunes_speaker
        volume_level: .4
    - service: input_boolean.turn_on
      entity_id: input_boolean.radio_garage

- alias: Garage off
  trigger:
    platform: state
    entity_id: input_boolean.radio_garage
    to: 'off'
  condition:
    - condition: state
      entity_id: media_player.ae_garage_airtunes_speaker
      state: 'on'
  action:
    - service: media_player.turn_off
      entity_id: media_player.ae_garage_airtunes_speaker
    - service: input_number.decrement
      entity_id: input_number.active_speakers
    - service: input_boolean.turn_off
      entity_id: input_boolean.radio_garage
