---
- alias: Keuken on
  trigger:
    - platform: state
      entity_id: sensor.hs_kitchen
      to: '1_click_up'
    - platform: state
      entity_id: input_boolean.radio_kitchen
      to: 'on'
  condition:
    - condition: state
      entity_id: media_player.ae_kitchen_airtunes_speaker
      state: 'off'
  action:
    - service: media_player.turn_on
      entity_id: media_player.ae_kitchen_airtunes_speaker
    - service: input_number.increment
      entity_id: input_number.active_speakers
    - service: media_player.volume_set
      data:
        entity_id: media_player.ae_kitchen_airtunes_speaker
        volume_level: .4
    - service: input_boolean.turn_on
      entity_id: input_boolean.radio_kitchen

- alias: Keuken next
  trigger:
    platform: state
    entity_id: sensor.hs_kitchen
    to: '1_click_up'
  condition:
    - condition: state
      entity_id: media_player.ae_kitchen_airtunes_speaker
      state: 'on'
  action:
    - service: media_player.media_next_track
      entity_id: media_player.itunes

- alias: Keuken off
  trigger:
    - platform: state
      entity_id: sensor.hs_kitchen
      to: '4_click_up'
    - platform: state
      entity_id: input_boolean.radio_kitchen
      to: 'off'
  condition:
    - condition: state
      entity_id: media_player.ae_kitchen_airtunes_speaker
      state: 'on'
  action:
    - service: media_player.turn_off
      entity_id: media_player.ae_kitchen_airtunes_speaker
    - service: input_number.decrement
      entity_id: input_number.active_speakers
    - service: input_boolean.turn_off
      entity_id: input_boolean.radio_kitchen

- alias: Keuken volume up
  trigger:
    platform: state
    entity_id: sensor.hs_kitchen
    to: '2_click_up'
  action:
    - service: media_player.volume_up
      entity_id: media_player.ae_kitchen_airtunes_speaker

- alias: Keuken volume down
  trigger:
    platform: state
    entity_id: sensor.hs_kitchen
    to: '3_click_up'
  action:
    - service: media_player.volume_down
      entity_id: media_player.ae_kitchen_airtunes_speaker
