---
- alias: any airplay speaker pressed on
  trigger:
    - platform: state
      entity_id:
        - sensor.hs_kitchen
        - sensor.hs_bathroom
      to: '1_click_up'
    - platform: state
      entity_id:
        - input_boolean.radio_kitchen
        - input_boolean.radio_bathroom
        - input_boolean.radio_garage
      to: 'on'
  condition:
    condition: or
    conditions:
      - condition: state
        entity_id: media_player.itunes
        state: 'paused'
      - condition: state
        entity_id: media_player.itunes
        state: 'idle'
  action:
    - service: media_player.shuffle_set
      data:
        entity_id: media_player.itunes
        shuffle: false
    - service: media_player.play_media
      data:
        entity_id: media_player.itunes
        media_content_type: playlist
        media_content_id: stream-radio
    - service: input_boolean.turn_on
      entity_id: input_boolean.itunes_active

- alias: last airplay speaker pressed off
  trigger:
    - platform: numeric_state
      entity_id: input_number.active_speakers
      below: 1
      for:
        seconds: 2
  action:
    - service: media_player.media_pause
      entity_id: media_player.itunes
    - service: input_boolean.turn_off
      entity_id: input_boolean.itunes_active
