---
homeassistant:
  name: Eindhoven
  latitude: 51.479751
  longitude: 5.503628
  elevation: 0
  unit_system: metric
  time_zone: Europe/Amsterdam
  customize: !include customize.yaml
  customize_domain: !include customize_domain.yaml
  auth_providers:
    - type: trusted_networks
      trusted_networks:
        - 192.168.0.71
    - type: homeassistant

logger:
  default: info
  # logs:
  #  homeassistant.components.config: debug
  #  homeassistant.components.config.automation: debug
  #  homeassistant.components.sensor.rest: debug
  #  custom_components.p2000: debug
  #  homeassistant.components.rfxtrx: debug
  #  homeassistant.components.mqtt: debug

#
# END MAIN CONFIG - START OTHER CONFIG #
#

cloud:
config:
conversation:

cure_waste:
  location: Eindhoven
  postalcode: !secret postcode
  housenumber: !secret housenumber

custom_updater:
  card_urls:
    - https://raw.githubusercontent.com/kalkih/mini-graph-card/master/tracker.json
    - https://raw.githubusercontent.com/kalkih/mini-media-player/master/tracker.json
    - https://raw.githubusercontent.com/kuuji/button-card/master/tracker.json
  component_urls:
    - https://raw.githubusercontent.com/robmarkcole/Hue-sensors-HASS/master/custom_updater.json
    - https://raw.githubusercontent.com/robmarkcole/Hue-sensors-HASS/master/custom_updater.json
    - https://raw.githubusercontent.com/custom-components/sensor.untappd/master/custom_updater.json

discovery:
  ignore:
    - roku

frontend:
  themes:
    solarized_dark: !include themes/solarized_dark.yaml

history:

hue:
  bridges:
    - host: !secret hue_ip
      allow_hue_groups: false

logbook:
map:

mqtt:
  password: !secret mqtt_password

media_player:
  - platform: itunes
    host: 192.168.0.56
  - platform: plex

mind:
  username: !secret mind_username
  password: !secret mind_password
  client_id: c030ad63a0e4433d86e4a36fc4047ce2
  client_secret: E97F8294804c49Cd83b0b9f0552577B2

nest:
  client_id: !secret nest_client_id
  client_secret: !secret nest_client_secret

p2000:
  regios: 22
  disciplines: 1,2,3
  distance: 1000
  interval: 30

rfxtrx:
  device: !secret rfxtrx_device
  dummy: false

recorder:
  purge_keep_days: 30

remote:
  - platform: harmony
    name: Living Room
    host: !secret harmony_ip # Slim Devices, Inc.

sabnzbd:
  api_key: !secret sab_apikey
  host: !secret sab_host
  sensors:
    - current_status
    - disk_free
    - month_size
    - total_size

speedtestdotnet:
  scan_interval:
    minutes: 10
  monitored_conditions:
    - ping

sun:
system_health:
updater:

#
# END OTHER CONFIG - START INCLUDES #
#

# alert: !include devices/alert.yaml
binary_sensor: !include devices/binary_sensor.yaml
device_tracker: !include devices/device_tracker.yaml
camera: !include devices/camera.yaml
climate: !include devices/climate.yaml
homekit: !include devices/homekit.yaml
input_select: !include devices/input_select.yaml
input_boolean: !include devices/input_boolean.yaml
input_number: !include devices/input_number.yaml
# input_text: !include devices/input_text.yaml
light: !include devices/light.yaml
notify: !include devices/notify.yaml
plant: !include devices/plant.yaml
rest_command: !include devices/rest_command.yaml
sensor: !include devices/sensor.yaml
shell_command: !include devices/shell_command.yaml
switch: !include devices/switch.yaml
utility_meter: !include devices/utility_meter.yaml
weather: !include devices/weather.yaml

group: !include groups.yaml
automation: !include_dir_merge_list automation/
script: !include scripts.yaml
