---
homeassistant:
  name: Eindhoven
  latitude: 51.479751
  longitude: 5.503628
  elevation: 0
  unit_system: metric
  time_zone: Europe/Amsterdam
  customize: !include customize.yaml
  customize_domain: !include customize_domain.yaml
  auth_providers:
    - type: trusted_networks
      trusted_networks:
        - 192.168.0.71
        - 192.168.0.127
    - type: homeassistant

logger:
  default: info
  # logs:
  #  homeassistant.components.webhook: debug
  #  homeassistant.components.config: debug
  #  homeassistant.components.config.automation: debug
  #  homeassistant.components.sensor.rest: debug
  #  custom_components.p2000: debug
  #  homeassistant.components.rfxtrx: debug
  #  homeassistant.components.mqtt: debug

#
# END MAIN CONFIG - START OTHER CONFIG #
#

apple_tv:

#cloud:
config:
conversation:

frontend:
  themes:
    solarized_dark: !include themes/solarized_dark.yaml

history:

logbook:
map:
mobile_app:

mqtt:
  password: !secret mqtt_password

media_player:
  - platform: plex

mind:
  username: !secret mind_username
  password: !secret mind_password
  client_id: c030ad63a0e4433d86e4a36fc4047ce2
  client_secret: E97F8294804c49Cd83b0b9f0552577B2

p2000:
  regios: 22
  disciplines: 1,2,3
  distance: 1000
  interval: 30

python_script:


recorder:
  purge_keep_days: 30
  db_url: sqlite:////data/home-assistant_v2.db

remote:
  - platform: harmony
    name: Living Room
    host: !secret harmony_ip # Slim Devices, Inc.

shopping_list:

speedtestdotnet:
  scan_interval:
    minutes: 10
  monitored_conditions:
    - ping

sun:
system_health:

telegram_bot:
  - platform: polling
    api_key: !secret telegram_api_key
    allowed_chat_ids:
      - !secret telegram_chat_id

tts:
  - platform: google_translate

updater:

#
# END OTHER CONFIG - START INCLUDES #
#

# alert: !include devices/alert.yaml
binary_sensor: !include devices/binary_sensor.yaml
device_tracker: !include devices/device_tracker.yaml
camera: !include devices/camera.yaml
cover: !include devices/cover.yaml
climate: !include devices/climate.yaml
homekit: !include devices/homekit.yaml
input_select: !include devices/input_select.yaml
input_boolean: !include devices/input_boolean.yaml
input_number: !include devices/input_number.yaml
# input_text: !include devices/input_text.yaml
light: !include devices/light.yaml
nest: !include devices/nest.yaml
notify: !include devices/notify.yaml
rest_command: !include devices/rest_command.yaml
rfxtrx: !include devices/rfxtrx.yaml
sensor: !include devices/sensor.yaml
shell_command: !include devices/shell_command.yaml
shelly: !include devices/shelly.yaml
switch: !include devices/switch.yaml
utility_meter: !include devices/utility_meter.yaml
vacuum: !include devices/vacuum.yaml
weather: !include devices/weather.yaml

group: !include groups.yaml
automation: !include_dir_merge_list automation/
script: !include scripts.yaml
