---
# evening routine
- alias: 'timer_evening_startevening'
  trigger:
    platform: sun
    event: sunset
    offset: "-01:00:00"
  action:
    - service: hue.hue_activate_scene
      data:
        group_name: "Woonkamer"
        scene_name: "DOM_evening"
    - service: hue.hue_activate_scene
      data:
        group_name: "Achtertuin"
        scene_name: "DOM_outdoor_evening"
    - service: light.turn_on
      entity_id:
        - light.hal_led_bak
        - light.carport
        - light.kerstboom

- alias: 'timer_evening_goodnight'
  trigger:
    platform: time
    at: '23:30:00'
  condition:
    - condition: state
      entity_id: input_boolean.is_it_party
      state: 'off'
  action:
    - service: light.turn_off
      entity_id:
        - light.h_schemerlamp
        - light.h_staande_lamp
        - light.h_tv_lamp
        - light.h_piano
        - light.hal_led_bak
        - light.h_outdoor_1
        - light.h_outdoor_2
        - light.h_outdoor_3
        - light.h_tafel_kamer
        - light.h_tafel_raam
        - light.kerstboom

- alias: 'timer_evening_carport'
  trigger:
    platform: sun
    event: sunrise
    offset: '01:00:00'
  action:
    - service: light.turn_off
      entity_id: light.carport
