---
- alias: Work from home start and reset
  trigger:
    platform: time
    at: '06:30:00'
  condition:
    - condition: state
      entity_id: input_boolean.homeworking_day
      state: 'on'
  action:
    - service: climate.set_operation_mode
      data:
        entity_id: climate.downstairs
        operation_mode: heat
    - service: climate.set_temperature
      data:
        entity_id: climate.downstairs
        temperature: 19.5
    - service: input_boolean.turn_off
      entity_id: input_boolean.homeworking_day
    - service: notify.pushover
      data:
        title: "Thuiswerken"
        message: "Verwarming ingesteld op 19.5C."
