---
- alias: Work from home enabled
  trigger:
    platform: state
    entity_id: input_boolean.homeworking_day
    to: 'on'
  action:
    - service: notify.pushover
      data:
        title: "Thuiswerken"
        message: "Morgenochtend staat de verwarming aan."

- alias: Work from home start and reset
  trigger:
    platform: time
    at: '06:00:00'
  condition:
    - condition: state
      entity_id: input_boolean.homeworking_day
      state: 'on'
  action:
    - service: climate.set_preset_mode
      data:
        entity_id: climate.woonkamer
        preset_mode: 'home'
    - service: input_boolean.turn_off
      entity_id: input_boolean.homeworking_day
    - service: notify.pushover
      data:
        title: "Thuiswerken"
        message: "Verwarming staat alvast aan."
