---
- alias: Work from home enabled
  trigger:
    platform: state
    entity_id: input_boolean.homeworking_day
    to: 'on'
  action:
    - service: notify.pushover
      data:
        title: "Thuiswerken"
        message: "Morgenochtend staat de verwarming aan."

- alias: Work from home start and reset
  trigger:
    platform: time
    at: '06:00:00'
  condition:
    - condition: state
      entity_id: input_boolean.homeworking_day
      state: 'on'
  action:
    - service: climate.set_operation_mode
      data:
        entity_id: climate.downstairs
        operation_mode: heat
    - service: climate.set_temperature
      data:
        entity_id: climate.downstairs
        temperature: 19.5
    - service: input_boolean.turn_off
      entity_id: input_boolean.homeworking_day
    - service: notify.pushover
      data:
        title: "Thuiswerken"
        message: "Verwarming staat alvast aan."
