---
# morning routine
- alias: 'timer_morning_startmorning'
  trigger:
    platform: time
    at: '06:15:00'
  condition:
    - condition: state
      entity_id: input_boolean.is_it_holiday
      state: 'off'
    - condition: time
      weekday:
        - mon
        - tue
        - wed
        - thu
        - fri
  action:
    - service: hue.hue_activate_scene
      data:
        group_name: "Woonkamer"
        scene_name: "DOM_morning"
    - service: light.turn_on
      entity_id: light.hal_led_bak

- alias: 'timer_morning_bathroom'
  trigger:
    platform: time
    at: '06:35:00'
  condition:
    - condition: state
      entity_id: input_boolean.is_it_holiday
      state: 'off'
    - condition: time
      weekday:
        - mon
        - tue
        - wed
        - thu
        - fri
    - condition: state
      entity_id: input_boolean.radio_bathroom
      state: 'off'
  action:
    - service: input_boolean.turn_on
      entity_id: input_boolean.radio_bathroom
    - service: light.turn_on
      entity_id: light.badkamer_lamp

- alias: 'timer_morning_breakfast'
  trigger:
    platform: time
    at: '06:45:00'
  condition:
    - condition: state
      entity_id: input_boolean.is_it_holiday
      state: 'off'
    - condition: time
      weekday:
        - mon
        - tue
        - wed
        - thu
        - fri
    - condition: state
      entity_id: input_boolean.radio_kitchen
      state: 'off'
  action:
    service: input_boolean.turn_on
    entity_id: input_boolean.radio_kitchen

- alias: 'timer_morning_tvon'
  trigger:
    platform: time
    at: '06:59:40'
  condition:
    - condition: state
      entity_id: input_boolean.is_it_holiday
      state: 'off'
    - condition: time
      weekday:
        - mon
        - tue
        - wed
        - thu
        - fri
  action:
    - service: input_boolean.turn_off
      entity_id: input_boolean.radio_kitchen
    - service: remote.turn_on
      entity_id: remote.living_room
      data:
        activity: "TV"
    - delay: '00:00:15'
    - service: remote.send_command
      entity_id: remote.living_room
      data:
        device: 42809894  # Entone DVR
        command:
          - 4

- alias: 'timer_morning_everythingoff'
  trigger:
    platform: time
    at: '07:30:00'
  condition:
    - condition: state
      entity_id: input_boolean.is_it_holiday
      state: 'off'
    - condition: time
      weekday:
        - mon
        - tue
        - wed
        - thu
        - fri
  action:
    - service: switch.turn_off
      entity_id:
        - switch.woonkamerverlichting
        - switch.tafelverlichting
    - service: light.turn_off
      entity_id:
        - light.hal_led_bak
        - light.badkamer_lamp
    - service: remote.turn_off
      entity_id: remote.living_room
    - service: input_boolean.turn_off
      entity_id: input_boolean.radio_bathroom
