---
- alias: Event doorbell
  trigger:
    - platform: state
      entity_id: binary_sensor.front_door_ding
      to: 'on'
  action:
    - service: notify.pushover
      data:
        title: "Deurbel"
        message: "De deurbel gaat"
        data:
          priority: -2
          file:
            url: !secret camera1_still
            auth: basic
            username: !secret camera1_username
            password: !secret camera1_password
    - service: notify.pushover
      data:
        title: "Deurbel"
        message: "De deurbel gaat"
        data:
          priority: 0
          file:
            url: !secret camera2_still
    - service: notify.telegram
      data:
        message: ''
        data:
          photo:
            - url: "{{ state_attr('camera.front_door', 'entity_picture') }}"
              caption: "Deurbel gaat"
    - delay: 30
    - service: notify.telegram
      data:
        message: ''
        data:
          video:
            - url: "{{ state_attr('camera.front_door', 'video_url') }}"
              caption: "Video van laatste bezoek"


- alias: Plex pause doorbell
  trigger:
    - platform: state
      entity_id: binary_sensor.front_door_ding
      to: 'on'
  condition:
    - condition: state
      entity_id: media_player.atv_living_room
      state: 'playing'
  action:
    - service: media_player.media_pause
      entity_id: media_player.atv_living_room

- alias: TV mute doorbell
  trigger:
    - platform: state
      entity_id: binary_sensor.front_door_ding
      to: 'on'
  condition:
    - condition: template
      value_template:
        '{{states.remote.living_room.attributes.current_activity == "TV" }}'
  action:
    - service: remote.send_command
      data:
        entity_id: remote.living_room
        device: 42809894 # Entone
        command:
          - Pause
