---
- alias: Doorbell rings
  trigger:
    - platform: event
      event_type: button_pressed
      event_data:
        entity_id: switch.deurbel
        state: "group on"
    - platform: state
      entity_id: input_boolean.send_photo
      to: 'on'
  action:
    - service: notify.pushover
      data:
        title: "Deurbel"
        message: "De deurbel gaat"
        data:
          priority: -2
          file:
            url: !secret camera1_still
            auth: basic
            username: !secret camera1_username
            password: !secret camera1_password
    - service: notify.pushover
      data:
        title: "Deurbel"
        message: "De deurbel gaat"
        data:
          priority: 0
          file:
            url: !secret camera2_still
    - service: switch.turn_off
      entity_id: switch.deurbel
    - service: input_boolean.turn_off
      entity_id: input_boolean.send_photo

- alias: Plex pause doorbell
  trigger:
    - platform: event
      event_type: button_pressed
      event_data:
        entity_id: switch.deurbel
        state: "group on"
  condition:
    - condition: state
      entity_id: media_player.kevin_mac_mini
      state: 'playing'
  action:
    - service: remote.send_command
      data:
        entity_id: remote.living_room
        device: 42809893  # Mac Mini
        command:
          - OK
          - Pause
        delay_secs: 0.6

- alias: TV mute doorbell
  trigger:
    - platform: event
      event_type: button_pressed
      event_data:
        entity_id: switch.deurbel
        state: "group on"
  condition:
    - condition: template
      value_template:
        '{{states.remote.living_room.attributes.current_activity == "TV" }}'
  action:
    - service: remote.send_command
      data:
        entity_id: remote.living_room
        device: 42809890  # Pioneer AV Receiver
        command:
          - Mute
