---
- alias: Event doorbell
  trigger:
    - platform: state
      entity_id: switch.ac_0efe9b2_1
  action:
    - service: input_boolean.turn_on
      entity_id: input_boolean.deurbel

- alias: Doorbell rings
  trigger:
    - platform: state
      entity_id:
        - input_boolean.deurbel
      to: 'on'
  action:
    - service: notify.pushover
      data:
        title: "Deurbel"
        message: "De deurbel gaat"
        data:
          priority: -2
          file:
            url: !secret camera1_still
            auth: basic
            username: !secret camera1_username
            password: !secret camera1_password
    - service: notify.pushover
      data:
        title: "Deurbel"
        message: "De deurbel gaat"
        data:
          priority: 0
          file:
            url: !secret camera2_still
    - service: input_boolean.turn_off
      entity_id: input_boolean.deurbel

- alias: Plex pause doorbell
  trigger:
    - platform: state
      entity_id: input_boolean.deurbel
      to: 'on'
  condition:
    - condition: state
      entity_id: media_player.atv_living_room
      state: 'playing'
  action:
    - service: media_player.media_pause
      entity_id: media_player.atv_living_room

- alias: TV mute doorbell
  trigger:
    - platform: state
      entity_id: input_boolean.deurbel
      to: 'on'
  condition:
    - condition: template
      value_template:
        '{{states.remote.living_room.attributes.current_activity == "TV" }}'
  action:
    - service: remote.send_command
      data:
        entity_id: remote.living_room
        device: 42809890  # Pioneer AV Receiver
        command:
          - Mute
