---
- alias: Doorbell rings
  trigger:
    platform: state
    entity_id: switch.deurbel
    to: 'on'
  action:
    - service: notify.pushover
      data:
        message: "De deurbel gaat"
        title: "Deurbel"
        data:
          priority: 0
    - service: switch.turn_off
      entity_id: switch.deurbel
#     - service: media_player.media_pause
#       entity_id: media_player.kevin__mac_mini
