---
- alias: Radio keuken on
  trigger:
    platform: state
    entity_id: switch.radio__keuken
    to: 'on'
  action:
    service: shell_command.radio_on
    data_template:
      radio_name: 'AE_Kitchen'
      volume: 40
