---
# keuken on
- alias: Radio keuken on
  trigger:
    platform: state
    entity_id: switch.radio__keuken
    to: 'on'
  action:
    service: shell_command.radio_on
    data_template:
      radio_name: 'AE_Kitchen'
      volume: 40

# keuken off
- alias: Radio keuken off
  trigger:
    platform: state
    entity_id: switch.radio__keuken
    to: 'off'
  action:
    service: shell_command.radio_off
    data_template:
      radio_name: 'AE_Kitchen'

# badkamer on
- alias: Radio badkamer on
  trigger:
    platform: state
    entity_id: switch.radio__badkamer
    to: 'on'
  action:
    service: shell_command.radio_on
    data_template:
      radio_name: 'AE_Bathroom'
      volume: 40

# badkamer off
- alias: Radio badkamer off
  trigger:
    platform: state
    entity_id: switch.radio__badkamer
    to: 'off'
  action:
    service: shell_command.radio_off
    data_template:
      radio_name: 'AE_Bathroom'

# garage on
- alias: Radio garage on
  trigger:
    platform: state
    entity_id: switch.radio__garage
    to: 'on'
  action:
    service: shell_command.radio_on
    data_template:
      radio_name: 'AE_Garage'
      volume: 40

# garage off
- alias: Radio garage off
  trigger:
    platform: state
    entity_id: switch.radio__garage
    to: 'off'
  action:
    service: shell_command.radio_off
    data_template:
      radio_name: 'AE_Garage'
