---
# Woonkamer on
- alias: Woonkamer verlichting aan
  trigger:
    platform: event
    event_type: rfxtrx_event
    event_data:
      id_string: '0b5468a:11'
  condition:
    condition: state
    entity_id: binary_sensor.ac_0b5468a_12
    state: 'on'
  action:
    - service: hue.hue_activate_scene
      data:
        group_name: "Woonkamer"
        scene_name: "DOM_evening"
    - service: light.turn_on
      data:
        entity_id: light.kerstboom

# Woonkamer off
- alias: Woonkamer verlichting uit
  trigger:
    platform: event
    event_type: rfxtrx_event
    event_data:
      id_string: '0b5468a:11'
  condition:
    condition: state
    entity_id: binary_sensor.ac_0b5468a_12
    state: 'off'
  action:
    service: light.turn_off
    data:
      entity_id:
        - light.h_schemerlamp
        - light.h_staande_lamp
        - light.h_tv_lamp
        - light.h_piano
        - light.hal_led_bak
        - light.h_outdoor_1
        - light.h_outdoor_2
        - light.h_outdoor_3
        - light.h_outdoor_4
        - light.h_outdoor_5
        - light.kerstboom

# Tafelverlichting on
- alias: Tafelverlichting aan
  trigger:
    platform: event
    event_type: rfxtrx_event
    event_data:
      id_string: '0b5468a:12'
  condition:
    condition: state
    entity_id: binary_sensor.ac_0b5468a_12
    state: 'on'
  action:
    service: light.turn_on
    data:
      entity_id:
        - light.h_tafel_kamer
        - light.h_tafel_raam

# Tafelverlichting off
- alias: Tafelverlichting uit
  trigger:
    platform: event
    event_type: rfxtrx_event
    event_data:
      id_string: '0b5468a:12'
  condition:
    condition: state
    entity_id: binary_sensor.ac_0b5468a_12
    state: 'off'
  action:
    service: light.turn_off
    data:
      entity_id:
        - light.h_tafel_kamer
        - light.h_tafel_raam
