---
# Woonkamer on
- alias: Woonkamer verlichting aan
  trigger:
    platform: state
    entity_id: switch.woonkamerverlichting
    to: 'on'
  action:
    - service: hue.hue_activate_scene
      data:
        group_name: "Living room"
        scene_name: "DOM_evening"
    - service: light.turn_on
      data:
        entity_id: light.kerstboom

# Woonkamer off
- alias: Woonkamer verlichting uit
  trigger:
    - platform: event  # not using state, because double-pressing can happen
      event_type: button_pressed
      event_data:
        entity_id: switch.woonkamerverlichting
        state: 'off'
    - platform: state
      entity_id: switch.woonkamerverlichting
      to: 'off'
  action:
    service: light.turn_off
    data:
      entity_id:
        - light.h_schemerlamp
        - light.h_staande_lamp
        - light.h_tv_lamp
        - light.h_piano
        - light.hal_led_bak
        - light.h_outdoor_1
        - light.h_outdoor_2
        - light.h_outdoor_3
        - light.h_outdoor_4
        - light.h_outdoor_5
        - light.kerstboom

# Tafelverlichting on
- alias: Tafelverlichting aan
  trigger:
    platform: state
    entity_id: switch.tafelverlichting
    to: 'on'
  action:
    service: light.turn_on
    data:
      entity_id:
        - light.h_tafel_kamer
        - light.h_tafel_raam
      rgb_color: [255, 198, 104]
      brightness: 127

# Tafelverlichting off
- alias: Tafelverlichting uit
  trigger:
    - platform: event  # not using state, because double-pressing can happen
      event_type: button_pressed
      event_data:
        entity_id: switch.tafelverlichting
        state: 'off'
    - platform: state
      entity_id: switch.tafelverlichting
      to: 'off'
  action:
    service: light.turn_off
    data:
      entity_id:
        - light.h_tafel_kamer
        - light.h_tafel_raam

# Badkamerverlichting on
- alias: Badkamerverlichting aan
  trigger:
    platform: state
    entity_id: switch.badkamerverlichting
    to: 'on'
  action:
    - service: hue.hue_activate_scene
      data:
        group_name: "Badkamer"
        scene_name: "DOM_bathroom_full"

# Badkamerverlichting off
- alias: Badkamerverlichting uit
  trigger:
    - platform: event
      event_type: button_pressed
      event_data:
        entity_id: switch.badkamerverlichting
        state: 'off'
    - platform: state
      entity_id: switch.badkamerverlichting
      to: 'off'
  action:
    service: light.turn_off
    data:
      entity_id:
        - light.h_badkamer_links
        - light.h_badkamer_midden
        - light.h_badkamer_rechts