---
- alias: Front door opens
  trigger:
    - platform: state
      entity_id: binary_sensor.shelly_door_frontdoor_door_window
      to: 'on'
  action:
    - service: notify.pushover
      data:
        title: "Voordeur geopend"
        message: "De voordeur is geopend"
        data:
          priority: -2
          file:
            url: !secret camera2_still
    - service: notify.telegram
      data:
        message: ''
        data:
          photo:
            - url: !secret camera2_still
              caption: "De voordeur is geopend"

- alias: Front door motion
  trigger:
    - platform: state
      entity_id: binary_sensor.front_door_motion
      to: 'on'
    - platform: state
      entity_id: input_boolean.tts_test
      to: 'on'
  action:
    - service: notify.pushover
      data:
        title: "Persoon bij de voordeur"
        message: "Er is een persoon bij de voordeur gedetecteerd"
        data:
          file:
            url: !secret camera2_still
    - service: notify.telegram
      data:
        message: ''
        data:
          photo:
            - url: !secret camera2_still
              caption: "Persoon bij de voordeur"
    - service: script.sonos_motion
      data_template:
        sonos_entity: media_player.sonos_keuken
        volume: "{{ states('input_number.doorbell_volume') }}"
    - service: script.sonos_motion
      data_template:
        sonos_entity: media_player.sonos_badkamer
        volume: "{{ states('input_number.doorbell_volume') }}"
    - service: input_boolean.turn_off
      entity_id: input_boolean.tts_test
