---
- alias: Front door opens
  trigger:
    - platform: state
      entity_id: binary_sensor.voordeur
      to: 'on'
  action:
    - service: notify.pushover
      data:
        title: "Voordeur geopend"
        message: "De voordeur is geopend"
        data:
          priority: -2
          file:
            url: !secret camera2_still
    - service: notify.telegram
      data:
        message: ''
        data:
          photo:
            - url: !secret camera2_still
              caption: "De voordeur is geopend"
