---
- alias: P2000 Notify
  trigger:
    platform: event
    event_type: p2000
  action:
    - service_template: notify.pushover
      data_template:
        title: "P2000"
        message: "{{ trigger.event.data.text }}"
        target: "kevin-iphone"
        data:
          priority: 0
