---
- alias: Afval notificatie
  trigger:
    platform: time
    at: '20:00:00'
  condition:
    condition: template
    value_template: "{% if not is_state('sensor.trash_tomorrow', 'None') %}true{% endif %}"
  action:
    - service: notify.pushover
      data_template:
        title: "Afval"
        message: "Morgen: {{ states.sensor.trash_tomorrow.state }}"

