---
- platform: rfxtrx
  automatic_add: false
  devices:
    09130052554555014e70:
      name: PIR hal
      device_class: motion
      off_delay:
        seconds: 30
        #    09130015d55555016370:
        #      name: PIR zolder
        #      device_class: motion
        #      off_delay:
        #        seconds: 30
    091300be1ee0e9018570:
      name: PIR kantoor
      device_class: motion
      off_delay:
        seconds: 30
    091300032891e9018870:
      name: PIR keuken
      device_class: motion
      off_delay:
        seconds: 30
    09130011e94fe9017c70:
      name: PIR slaapkamer
      device_class: motion
      off_delay:
        seconds: 30
    091300258cefa9017a70:
      name: PIR woonkamer
      device_class: motion
      off_delay:
        seconds: 30
    0b11000500fbc7ce0a010f50:
      name: Voordeur
      device_class: door
    0b11000d00eb4d860a010f50:
      name: Deur keuken
      device_class: door
    0b11001801071a760a010f50:
      name: Raam Emma
      device_class: window
    0b11001d01002a360a010f40:
      name: Raam slaapkamer
      device_class: window
    0b11002400e19a520a010f40:
      name: Raam zolder
      device_class: window
    0b1100290111eade0a010f50:
      name: Raam kantoor
      device_class: window
    0b11003100fc0aea0a010f50:
      name: Deur woonkamer
      device_class: door
    0b11003900eb56360a000040:
      name: Schuurdeur
      device_class: door
    0b11003a00eb573e0a000050:
      name: Garagedeur
      device_class: garage_door
    09130010a499ee013940:
      name: Deur Emma open
      device_class: door
      data_bits: 4
      command_on: 0xe
      off_delay:
        seconds: 2
    09130016a499e7013b50:
      name: Deur Emma close
      device_class: door
      data_bits: 4
      command_on: 0x7
      off_delay:
        seconds: 2
    09130018a499eb013b50:
      name: Deur Emma alarm
      device_class: door
      data_bits: 4
      command_on: 0xb
      off_delay:
        seconds: 2
- platform: workday
  name: Werkdag vandaag
  country: NL
- platform: workday
  name: Werkdag morgen
  country: NL
  days_offset: 1
- platform: template
  sensors:
    door_emma:
      device_class: door
      value_template: "{{ is_state('input_boolean.door_emma', 'on') }}"
