---
- platform: workday
  name: Werkdag vandaag
  country: NL
- platform: workday
  name: Werkdag morgen
  country: NL
  days_offset: 1
- platform: template
  sensors:
    voordeur:
      device_class: door
      value_template: "{{ is_state('binary_sensor.ac_0fbc7ce_10', 'on') }}"
    deur_keuken:
      device_class: door
      value_template: "{{ is_state('binary_sensor.ac_0eb4d86_10', 'on') }}"
    deur_slaapkamer:
      device_class: door
      value_template: "{{ is_state('binary_sensor.ac_0e19a52_10', 'on') }}"
    deur_woonkamer:
      device_class: door
      value_template: "{{ is_state('binary_sensor.ac_0fc0aea_10', 'on') }}"
    schuurdeur:
      device_class: door
      value_template: "{{ is_state('binary_sensor.ac_0eb5636_10', 'on') }}"
    garagedeur:
      device_class: garage_door
      value_template: "{{ is_state('binary_sensor.ac_0eb573e_10', 'on') }}"
    pir_hal:
      device_class: motion
      value_template: "{{ is_state('binary_sensor.pt2262_554555', 'on') }}"
    pir_kantoor:
      device_class: motion
      value_template: "{{ is_state('binary_sensor.pt2262_1ee0e9', 'on') }}"
    pir_keuken:
      device_class: motion
      value_template: "{{ is_state('binary_sensor.pt2262_2891e9', 'on') }}"
    pir_slaapkamer:
      device_class: motion
      value_template: "{{ is_state('binary_sensor.pt2262_e94fe9', 'on') }}"
    pir_woonkamer:
      device_class: motion
      value_template: "{{ is_state('binary_sensor.pt2262_8cefa9', 'on') }}"
    raam_emma:
      device_class: window
      value_template: "{{ is_state('binary_sensor.ac_1071a76_10', 'on') }}"
    raam_slaapkamer:
      device_class: window
      value_template: "{{ is_state('binary_sensor.ac_1002a36_10', 'on') }}"
    raam_kantoor:
      device_class: window
      value_template: "{{ is_state('binary_sensor.ac_111eade_10', 'on') }}"
    deur_emma:
      device_class: door
      value_template: "{{ is_state('binary_sensor.pt2262_a499ee', 'on') }}"
    deur_kantoor:
      device_class: door
      value_template: "{{ is_state('binary_sensor.pt2262_e116ae', 'on') }}"
    brandalarm_woonkamer:
      device_class: smoke
      value_template: "{{ is_state('binary_sensor.kd101_smoke_detector_05f100_32', 'on') }}"
    brandalarm_keuken:
      device_class: smoke
      value_template: "{{ is_state('binary_sensor.kd101_smoke_detector_4c4000_32', 'on') }}"
    brandalarm_zolder:
      device_class: smoke
      value_template: "{{ is_state('binary_sensor.kd101_smoke_detector_d48600_32', 'on') }}"
    deurbel:
      device_class: door
      value_template: "{{ is_state('input_boolean.deurbel', 'on') }}"
