---
- platform: huesensor
- platform: yr
  monitored_conditions:
    - temperature
    - precipitation
    - fog
    - cloudiness
    - symbol
# - platform: yweather
#   name: Yahoo vandaag
#   monitored_conditions:
#     - weather
#     - weather_current
#     - temp_min
#     - temp_max
- platform: moon
# - platform: fitbit
#   monitored_resources:
#     - activities/distance
#     - activities/heart
#     - activities/steps
- platform: time_date
  display_options:
    - 'time'
    - 'date'
- platform: dsmr
  port: !secret dsmr_device
  dsmr_version: 4
- platform: rfxtrx
  automatic_add: false
  devices:
    0a520702390e00b72f0149:
      name: Temperatuur logeerkamer
    0a5207035c0e00cc3c0149:
      name: Temperatuur slaapkamer
#     0a52071d7c0e00d32e0149:
#       name: Temperatuur badkamer
    0a520734530e00d52c0159:
      name: Temperatuur garage
    0a520302bf010075430049:
      name: Temperatuur buiten
    0a520c1f000200c8050269:
      name: Temperatuur Yucca - palmboom
    0a520c35000100dc050269:
      name: Temperatuur Peace Lily - witte bloem
    0820032805f1000650:
      name: Brandalarm woonkamer
      fire_event: true
    082003304c40000650:
      name: Brandalarm keuken
      fire_event: true
    08200335d486000640:
      name: Brandalarm zolder
      fire_event: true
- platform: command_line
  name: CPU Temperatuur
  command: "cat /sys/class/thermal/thermal_zone0/temp"
  unit_of_measurement: "C"
  value_template: '{{ value | multiply(0.001) | round(1) }}'
- platform: uptime
- platform: version
- platform: systemmonitor
  resources:
    - type: disk_use_percent
      arg: /home
    - type: memory_free
    - type: load_5m
    - type: network_in
      arg: eth0
    - type: network_out
      arg: eth0
    - type: processor_use
    - type: last_boot
# - platform: command_line
#   name: Internal IP WiFi
#   command: "ip addr show wlan0 | grep -Po 'inet \\K[\\d.]+'"
- platform: command_line
  name: Internal IP LAN
  command: "ip addr show eth0 | grep -Po 'inet \\K[\\d.]+'"
- platform: command_line
  name: External IP
  command: "/usr/bin/curl kvanhoorn.nl/myip/"
- platform: command_line
  name: Database size
  command: 'ls -hl /data/home-assistant_v2.db | cut -d " " -f5'
- platform: darksky
  api_key: 2cbc3be161a2e13481e8c56cf491c525
  forecast:
    - 0
    - 1
  monitored_conditions:
    - summary
    - icon
    - precip_type
    - precip_probability
    - temperature
    - apparent_temperature
    - wind_speed
    - humidity
    - visibility
    - temperature_high
    - temperature_low
    - uv_index
- platform: feedparser
  name: Omroep Brabant Zuid-Oost
  url: !secret omroepbrabant_rss_url
  attributes:
    - summary
    - link
- platform: feedparser
  name: NOS Algemeen
  url: !secret nosalgemeen_rss_url
  attributes:
    - link
- platform: feedparser
  name: nu.nl Algemeen
  url: !secret nunlalgemeen_rss_url
  attributes:
    - link
    - summary
- platform: template
  sensors:
    peace_lily_witte_bloem_humidity:
      # can't cut this up into two lines :(
      value_template: "{{states.sensor.temperatuur_peace_lily_witte_bloem_temperature.attributes.Humidity
        | int}}"
      friendly_name: 'Peace Lily - witte bloem vochtigheid'
      unit_of_measurement: '%'
    yucca_palmboom_humidity:
      # can't cut this up into two lines :(
      value_template: "{{states.sensor.temperatuur_yucca_palmboom_temperature.attributes.Humidity
        | int}}"
      friendly_name: 'Yucca - palmboom vochtigheid'
      unit_of_measurement: '%'
    static_battery:
      value_template: "{{100}}"
      unit_of_measurement: '%'
    static_conductivity:
      value_template: "{{10}}"
      unit_of_measurement: 'ec'
    static_brightness:
      value_template: "{{10}}"
      unit_of_measurement: 'lm'
    livingroom_temperature:
      value_template: "{{states.climate.woonkamer.attributes.current_temperature}}"
      friendly_name: 'Woonkamer'
      unit_of_measurement: '°C'
    car_address:
      value_template: "{{states.device_tracker.nr767t.attributes.street}},
        {{states.device_tracker.nr767t.attributes.city}},
        {{states.device_tracker.nr767t.attributes.country}}"
      friendly_name: 'Adres'
    long_time_not_seen_devices:
      friendly_name: 'Meer dan 3 dagen niet gezien'
      icon_template: 'mdi:battery'
      value_template: >
        {% for entity in (states | selectattr('entity_id','in', state_attr('group.long_battery_devices','entity_id'))) %}
          {%- if (as_timestamp(now()) - as_timestamp(entity.last_updated) > (60 * 60 * 24 * 3)) -%}
            {{ entity.name }},
          {%- endif -%}
        {% endfor %}
    short_time_not_seen_devices:
      friendly_name: 'Meer dan 6 uur niet gezien'
      icon_template: 'mdi:battery'
      value_template: >
        {% for entity in (states | selectattr('entity_id','in', state_attr('group.short_battery_devices','entity_id'))) %}
          {%- if (as_timestamp(now()) - as_timestamp(entity.last_updated) > (60 * 60 * 6)) -%}
            {{ entity.name }},
          {%- endif -%}
        {% endfor %}
    bedroom_vs_outside_temperature:
      friendly_name: 'Slaapkamer vs buiten temperatuur'
      icon_template: 'mdi:temperature-celsius'
      unit_of_measurement: '°C'
      value_template: >
        {{ (states.sensor.temperatuur_slaapkamer_temperature.state | float -
        states.sensor.temperatuur_buiten_temperature.state | float) |
        float | round(2) }}
    living_vs_outside_temperature:
      friendly_name: 'Woonkamer vs buiten temperatuur'
      icon_template: 'mdi:temperature-celsius'
      unit_of_measurement: '°C'
      value_template: >
        {{ (states.climate.woonkamer.attributes.current_temperature | float -
        states.sensor.temperatuur_buiten_temperature.state | float) |
        float | round(2) }}
    untappd_full_checkin:
      friendly_name: Untappd last checkin full
      entity_id: sensor.untappd_last_check_in_kvanhoorn
      value_template: >
        {{ states.sensor.untappd_last_check_in_kvanhoorn.attributes.brewery }} -
        {{ states.sensor.untappd_last_check_in_kvanhoorn.attributes.beer }}
        ({{ states.sensor.untappd_last_check_in_kvanhoorn.attributes.abv }})
    next_setting:
      friendly_name: Zonsondergang
      entity_id: sun.sun
      value_template: >
        {{ as_timestamp(states.sun.sun.attributes.next_setting) | timestamp_custom('%H:%M') }}
    next_rising:
      friendly_name: Zonsopgang
      entity_id: sun.sun
      value_template: >
        {{ as_timestamp(states.sun.sun.attributes.next_rising) | timestamp_custom('%H:%M') }}
    daily_power:
      friendly_name: Daily Power
      icon_template: 'mdi:counter'
      unit_of_measurement: kWh
      value_template: "{{ states('sensor.daily_power_offpeak')|float + states('sensor.daily_power_peak')|float }}"
    monthly_power:
      friendly_name: Monthly Power
      icon_template: 'mdi:counter'
      unit_of_measurement: kWh
      value_template: "{{ states('sensor.monthly_power_offpeak')|float + states('sensor.monthly_power_peak')|float }}"
- platform: mqtt
  name: Sous vide
  state_topic: anova/timer
  value_template: "{{ (((value_json.timer | int) * 60) - 3600) | timestamp_custom('%H:%M') }}"
  icon: 'mdi:timer'
- platform: mqtt
  state_topic: igrill/bbq/probe1
  name: "Probe 1"
  qos: 0
  unit_of_measurement: "°C"
- platform: mqtt
  state_topic: igrill/bbq/probe2
  name: "Probe 2"
  qos: 0
  unit_of_measurement: "°C"
- platform: mqtt
  state_topic: igrill/bbq/probe3
  name: "Probe 3"
  qos: 0
  unit_of_measurement: "°C"
- platform: mqtt
  state_topic: igrill/bbq/probe4
  name: "Probe 4"
  qos: 0
  unit_of_measurement: "°C"
- platform: mqtt
  state_topic: igrill/bbq/battery
  name: "igrill battery"
  qos: 0
  unit_of_measurement: "%"
- platform: mqtt
  state_topic: igrill/bbq_mini/probe1
  name: "Mini Probe 1"
  qos: 0
  unit_of_measurement: "°C"
- platform: mqtt
  state_topic: igrill/bbq_mini/battery
  name: "igrill mini battery"
  qos: 0
  unit_of_measurement: "%"
- platform: scrape
  name: Euro95
  resource: !secret fuel_prices_nationwide
  select: ".table .table-row:nth-of-type(2) div:nth-of-type(3)"
  value_template: "{{ value.split(' ')[1].replace(',', '.') | float }}"
  scan_interval: 3600
- platform: scrape
  name: Diesel
  resource: !secret fuel_prices_nationwide
  select: ".table .table-row:nth-of-type(3) div:nth-of-type(3)"
  value_template: "{{ value.split(' ')[1].replace(',', '.') | float }}"
  scan_interval: 3600
# - platform: scrape
#   name: Euro95 (Tinq)
#   resource: !secret fuel_prices_local
#   select: "#station-prijzen tr:nth-of-type(4) td:nth-of-type(2)"
#   value_template: "{{ value.split(\"\xa0\")[1].replace(',', '.') | float }}"
#   scan_interval: 3600
#   verify_ssl: false
# - platform: scrape
#   name: Diesel (Tinq)
#   resource: !secret fuel_prices_local
#   select: "#station-prijzen tr:nth-of-type(3) td:nth-of-type(2)"
#   value_template: "{{ value.split(\"\xa0\")[1].replace(',', '.') | float }}"
#   scan_interval: 3600
#   verify_ssl: false
- platform: launch_library
- platform: ovapi
  name: Bus 4
  timing_point_code: !secret busstop_code
  show_future_departures: 2
- platform: untappd
  username: kvanhoorn
  id: !secret untappd_id
  secret: !secret untappd_secret
- platform: postcodeloterij
  postcode: !secret postcode
- platform: synologydsm
  host: !secret synology_host
  username: !secret synology_username
  password: !secret synology_password
  monitored_conditions:
    - cpu_other_load
    - cpu_user_load
    - cpu_system_load
    - cpu_total_load
    - cpu_1min_load
    - cpu_5min_load
    - cpu_15min_load
    - memory_real_usage
    - memory_size
    - memory_cached
    - memory_available_swap
    - memory_available_real
    - memory_total_swap
    - memory_total_real
    - network_up
    - network_down
    - disk_name
    - disk_device
    - disk_smart_status
    - disk_status
    - disk_exceed_bad_sector_thr
    - disk_below_remain_life_thr
    - disk_temp
    - volume_status
    - volume_device_type
    - volume_size_total
    - volume_size_used
    - volume_percentage_used
    - volume_disk_temp_avg
    - volume_disk_temp_max
- platform: afvalwijzer
  zipcode: !secret postcode
  housenumber: !secret housenumber
  count_today: true
