---
- platform: template
  switches:
    outdoor_lightning:
      value_template: "{{ states.light.h_outdoor_1.state == 'on' 
        and states.light.h_outdoor_4.state == 'on' }}"
      turn_on:
        service: hue.hue_activate_scene
        data:
          group_name: "Achtertuin"
          scene_name: "DOM_outdoor_evening"
      turn_off:
        service: light.turn_off
        data:
          entity_id:
            - light.h_outdoor_1
            - light.h_outdoor_2
            - light.h_outdoor_3
            - light.h_outdoor_4
            - light.h_outdoor_5
    bathroom_lightning:
      value_template: "{{ states.light.h_badkamer_links.state == 'on'
        and states.light.h_badkamer_rechts.state == 'on' }}"
      turn_on:
        service: light.turn_on
        data:
          entity_id:
            - light.h_badkamer_links
            - light.h_badkamer_midden
            - light.h_badkamer_rechts
      turn_off:
        service: light.turn_off
        data:
          entity_id:
            - light.h_badkamer_links
            - light.h_badkamer_midden
            - light.h_badkamer_rechts
- platform: mqtt
  name: Sous vide
  state_topic: anova/timer
  command_topic: anova/command/timer_run
  payload_on: 'running'
  payload_off: 'stopped'
  state_on: 'running'
  state_off: 'stopped'
  optimistic: false
  retain: true
  value_template: "{{ value_json.timer_state }}"
  icon: 'mdi:timer'
