---
- platform: rfxtrx
  automatic_add: false
  devices:
    0b11001f00b5468a0c010f70:
      name: Tafelverlichting
      fire_event: true
    0b11002300b5468a0b010f60:
      name: Woonkamerverlichting
      fire_event: true
    0b11003100e1e5ea0b010f50:
      name: Badkamerverlichting
      fire_event: true
#     0b11002701233d660b010f40:
#       name: Radio - Keuken
#       fire_event: true
#     0b11002b01233d660c010f50:
#       name: Radio - Garage
#       fire_event: true
#     0b11002d00e1e5ea0c010f50:
#       name: Radio - Badkamer
#       fire_event: true
    0b11000b00efe9b201040f60:
      name: Deurbel
      fire_event: true
- platform: template
  switches:
    outdoor_lightning:
      value_template: "{{ states.light.h_outdoor_1.state == 'on' 
        and states.light.h_outdoor_4.state == 'on' }}"
      turn_on:
        service: hue.hue_activate_scene
        data:
          group_name: "Backyard"
          scene_name: "DOM_outdoor_evening"
      turn_off:
        service: light.turn_off
        data:
          entity_id:
            - light.h_outdoor_1
            - light.h_outdoor_2
            - light.h_outdoor_3
            - light.hue_outdoor_pedestal_1
            - light.hue_outdoor_pedestal_1_2
- platform: mqtt
  name: Sous vide
  state_topic: anova/timer
  command_topic: anova/command/timer_run
  payload_on: 'running'
  payload_off: 'stopped'
  state_on: 'running'
  state_off: 'stopped'
  optimistic: false
  retain: true
  value_template: "{{ value_json.timer_state }}"
  icon: 'mdi:timer'
