---
- alias: Higher volume doorbell
  trigger:
    - platform: state
      entity_id: binary_sensor.shelly_door_emma_door_window
      to: 'on'
  action:
    - service: input_number.set_value
      data:
        entity_id: input_number.doorbell_volume
        value: .5

- alias: Lower volume doorbelld
  trigger:
    - platform: state
      entity_id: binary_sensor.shelly_door_emma_door_window
      to: 'off'
  action:
    - service: input_number.set_value
      data:
        entity_id: input_number.doorbell_volume
        value: .2
