---
- alias: Turn on upstairs doorbell ring
  trigger:
    - platform: state
      entity_id: binary_sensor.deur_emma
      to: 'on'
  condition:
    - condition: time
      after: '07:00:00'
      before: '20:00:00'
  action:
    - service: light.turn_on
      entity_id: light.h_doorbell

- alias: Turn off upstairs doorbell ring
  trigger:
    - platform: state
      entity_id: binary_sensor.deur_emma
      to: 'off'
  action:
    - service: light.turn_off
      entity_id: light.h_doorbell
