---
- alias: Change Harmony Remote input
  trigger:
    platform: state
    entity_id: remote.living_room
  action:
    service: input_select.select_option
    data_template:
      entity_id: input_select.harmony_hub
      option: >
        {{ states.remote.living_room.attributes.current_activity }}

- alias: Change Harmony Select input
  trigger:
    platform: state
    entity_id: input_select.harmony_hub
  action:
    service: remote.turn_on
    data_template:
      entity_id: remote.living_room
      activity: >
        {% if is_state("input_select.harmony_hub", "TV") %}
          41424370
        {% elif is_state("input_select.harmony_hub", "Apple TV") %}
          41424379
        {% elif is_state("input_select.harmony_hub", "PowerOff") %}
          -1
        {% else %}
        {% endif %}
