---
- alias: Synology disk usage
  trigger:
    platform: numeric_state
    entity_id:
      - sensor.synology_dsm_volume_used_volume_1
      - sensor.synology_dsm_volume_used_volume_2
      - sensor.synology_dsm_volume_used_volume_3
      - sensor.synology_dsm_volume_used_volume_4
    above: 98
    for:
      minutes: 10
  action:
    - service: notify.pushover
      data_template:
        title: "Synology Disk vol"
        message: >
          "Disk {{ trigger.to_state.name }} is
          {{ trigger.to_state.state }}% vol!"
        data:
          sound: "siren"
          priority: 2
          expire: 3600
          retry: 60

- alias: Raspberry Pi disk usage alarm
  trigger:
    platform: numeric_state
    entity_id: sensor.disk_use_percent_home
    above: 90
    for:
      minutes: 5
  action:
    - service: notify.pushover
      data_template:
        title: "Raspberry Pi disk usage"
        message: "Raspbery Pi disk gebruik >
          {{ states.sensor.disk_use_percent_home.state }}%"
        data:
          sound: "siren"
          priority: 2
          expire: 3600
          retry: 60
