---
- alias: PIR alarm
  trigger:
    platform: state
    entity_id:
      - binary_sensor.pir_hal
      # - binary_sensor.pir_zolder
      # - binary_sensor.hm_motion_backyard
    to: 'on'
  condition:
    condition: state
    entity_id: input_boolean.someone_home
    state: 'off'
  action:
    - service: notify.pushover
      data_template:
        message: "Er is beweging gedecteerd door
          {{trigger.to_state.attributes.friendly_name}}"
        title: "Beweging"
        data:
          sound: "siren"
          priority: 2
          expire: 3600
          retry: 60

# use PIR to turn on light at night
- alias: PIR turn hall on
  trigger:
    platform: state
    entity_id: binary_sensor.pir_hal
    to: 'on'
  condition:
    condition: state
    entity_id: input_boolean.is_it_night
    state: 'on'
  action:
    service: light.turn_on
    entity_id: light.hal_led_bak

# and turn it back off
- alias: PIR turn hall off
  trigger:
    platform: state
    entity_id: binary_sensor.pir_hal
    to: 'off'
    for:
      minutes: 2
  condition:
    condition: state
    entity_id: input_boolean.is_it_night
    state: 'on'
  action:
    service: light.turn_off
    entity_id: light.hal_led_bak

# use PIR to turn on light
# - alias: PIR turn staircase closet on
#   trigger:
#     platform: state
#     entity_id: binary_sensor.hm_hall_motion
#     to: 'on'
#   action:
#     service: light.turn_on
#     entity_id: light.h_gangkast

# and turn it back off
# - alias: PIR turn staircase closet off
#   trigger:
#     platform: state
#     entity_id: binary_sensor.hm_hall_motion
#     to: 'off'
#     for:
#       minutes: 1
#   action:
#     service: light.turn_off
#     entity_id: light.h_gangkast

# use PIR to turn on attic lights
- alias: PIR turn attic on
  trigger:
    platform: state
    entity_id: binary_sensor.pir_zolder
    to: 'on'
  action:
    service: light.turn_on
    entity_id: group.attic_lights

# use PIR to turn off attic lights
- alias: PIR turn attic off
  trigger:
    platform: state
    entity_id: binary_sensor.pir_zolder
    to: 'off'
    for:
      minutes: 2
  action:
    service: light.turn_off
    entity_id: group.attic_lights

# use PIR to turn on study lights
- alias: PIR turn study on
  trigger:
    platform: state
    entity_id: binary_sensor.pir_studeerkamer
    to: 'on'
  action:
    service: light.turn_on
    entity_id: light.bureaulamp

# use PIR to turn off study lights
- alias: PIR turn study off
  trigger:
    platform: state
    entity_id: binary_sensor.pir_studeerkamer
    to: 'off'
    for:
      minutes: 2
  action:
    service: light.turn_off
    entity_id: light.bureaulamp

# use PIR to turn on outside
- alias: PIR turn backyard on during nightalarm
  trigger:
    platform: state
    entity_id: binary_sensor.hm_motion_backyard
    to: 'on'
  condition:
    condition: state
    entity_id: input_boolean.is_it_night
    state: 'on'
  action:
    service: hue.hue_activate_scene
    data:
      group_name: "Achtertuin"
      scene_name: "DOM_overday"

# use PIR to turn on outside
- alias: PIR turn backyard on during dark
  trigger:
    platform: state
    entity_id: binary_sensor.hm_motion_backyard
    to: 'on'
  condition:
    - condition: sun
      after: sunset
    - condition: state
      entity_id: input_boolean.is_it_night
      state: 'off'
  action:
    service: hue.hue_activate_scene
    data:
      group_name: "Achtertuin"
      scene_name: "DOM_outdoor_evening"

# use PIR to turn off outside
- alias: PIR turn backyard off during nightalarm
  trigger:
    platform: state
    entity_id: binary_sensor.hm_motion_backyard
    to: 'off'
    for:
      minutes: 1
  condition:
    condition: state
    entity_id: input_boolean.is_it_night
    state: 'on'
  action:
    service: light.turn_off
    entity_id: group.outdoor_lights
