---
- alias: PIR alarm
  trigger:
    platform: state
    entity_id:
      - binary_sensor.pir_hal
      - binary_sensor.pir_zolder
    to: 'on'
  condition:
    condition: state
    entity_id: input_boolean.someone_home
    state: 'off'
  action:
    - service: notify.pushover
      data_template:
        message: "Er is beweging gedecteerd door
          {{trigger.to_state.attributes.friendly_name}}"
        title: "Beweging"
        data:
          sound: "siren"
          priority: 2
          expire: 3600
          retry: 60

# use PIR to turn on light at night
- alias: PIR turn hall on
  trigger:
    platform: state
    entity_id: binary_sensor.pir_hal
    to: 'on'
  condition:
    condition: state
    entity_id: input_boolean.is_it_night
    state: 'on'
  action:
    service: light.turn_on
    entity_id: light.hal_led_bak

# and turn it back off
- alias: PIR turn hall off
  trigger:
    platform: state
    entity_id: binary_sensor.pir_hal
    to: 'off'
    for:
      minutes: 10
  condition:
    condition: state
    entity_id: input_boolean.is_it_night
    state: 'on'
  action:
    service: light.turn_off
    entity_id: light.hal_led_bak

# use PIR to turn on attic lights
- alias: PIR turn attic on
  trigger:
    platform: state
    entity_id: binary_sensor.pir_zolder
    to: 'on'
  action:
    service: light.turn_on
    entity_id: group.attic_lights

# use PIR to turn on attic lights
- alias: PIR turn attic off
  trigger:
    platform: state
    entity_id: binary_sensor.pir_zolder
    to: 'off'
    for:
      minutes: 10
  action:
    service: light.turn_off
    entity_id: group.attic_lights
