---
- alias: Plant humidity warning
  trigger:
    platform: numeric_state
    entity_id:
      - sensor.plant1_humidity
      - sensor.plant2_humidity
    below: 50
    for:
      minutes: 30
  action:
    - service: notify.pushover
      data_template:
        title: "Plant heeft dorst"
        message: "{{ trigger.to_state.attributes.friendly_name }} onder 50%"
        data:
          priority: 0

- alias: Plant humidity alarm
  trigger:
    platform: numeric_state
    entity_id:
      - sensor.plant1_humidity
      - sensor.plant2_humidity
    below: 30
    for:
      minutes: 30
  action:
    - service: notify.pushover
      data_template:
        title: "Plant heeft veel dorst"
        message: "{{ trigger.to_state.attributes.friendly_name }} onder 30%"
        data:
          priority: 1

- alias: Plant humidity ok
  trigger:
    platform: numeric_state
    entity_id:
      - sensor.plant1_humidity
      - sensor.plant2_humidity
    above: 50
    for:
      minutes: 30
  action:
    - service: notify.pushover
      data_template:
        title: "Plant heeft geen dorst meer"
        message: "{{ trigger.to_state.attributes.friendly_name }} boven 50%"
